### ISSUE TITLE
Keyboard only shows as AZERTY

### ISSUE THREAD

**Issue by Bijan-A** [robertosartori/SwypeRow#1]
With the latest couple updates, my keyboard is showing up as AZERTY instead of QWERTY. How am I supposed to change it?

**Comment by roberto-sartori-gl** [comment]
Go into Swype settings, languages, to the right you will see a keyboard: press it and you will be able to change between 'azerty' and 'qwerty'.

**Comment by Bijan-A** [comment]
It has been set on QWERTY this whole time.

**Comment by roberto-sartori-gl** [comment]
What language are you using?

**Comment by Bijan-A** [comment]
English, QWERTY

**Comment by roberto-sartori-gl** [comment]
Try disabling and enabling the module (And reboot between that). I'm also using that keyboard without problems, like a lot of other people...
