### ISSUE TITLE
faild to add new XML

### ISSUE THREAD

**Issue by ttv20** [robertosartori/SwypeRow#4]
I successfuly replace custom kbd_qwerty_panlatin.xml
I tryed to add kbd_hebrew.xml but it not worked (the hebrew keyboard didn't changed)

how to add a new XML file correctly?

**Comment by roberto-sartori-gl** [comment]
Have you recompiled the apk or only insert your xml in my apk?

**Comment by ttv20** [comment]
I tryed to only insert XML and to recompile

**Comment by roberto-sartori-gl** [comment]
If you have recompiled the apk after put your xml in res/raw folder, it should work automatically. Check if Android Studio\Eclipse see your xml in apk's structure.

**Comment by ttv20** [comment]
the eclipce show this error:
Content is not allowed in prolog.  
kbd_hebrew.xml  
Android XML Format Problem

**Comment by roberto-sartori-gl** [comment]
Refresh and clean the project, that error is normal. It will disappear after that.

**Comment by ttv20** [comment]
Now its better. in hebrew its show only the suggestion row...
Probably something wrong in the XML
thanks!

**Comment by roberto-sartori-gl** [comment]
Yes, it means that XML is loaded correctly.
